import { sql } from "drizzle-orm";
import { timestamp, uuid } from "drizzle-orm/pg-core";

/*
 * Column helpers every table starts from, so ids and timestamps look the same everywhere.
 * Use them as `id: id()`, `createdAt: createdAt()`, `updatedAt: updatedAt()`.
 */

/** A UUIDv7 primary key, generated by Postgres 18. Time-ordered, so inserts stay fast. */
export const id = () => uuid("id").primaryKey().default(sql`uuidv7()`);

/** When the row was created. `timestamptz`, so it is unambiguous across time zones. */
export const createdAt = () =>
  timestamp("created_at", { withTimezone: true }).notNull().defaultNow();

/** When the row was last changed. Drizzle sets it on every update made through it. */
export const updatedAt = () =>
  timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());
