import type { ColorScheme } from "./theme";
import { theme, themeVariableNames, tokenNames } from "./theme";

/*
 * Turns the theme into the files that are generated from it. Pure functions: the generator
 * script writes their output, and a test checks the files on disk still equal it.
 */

const banner = (usage: string) =>
  `/*\n * GENERATED by \`pnpm theme:generate\` from packages/config/src/theme.ts.\n * Do not edit by hand: change the theme there and run the generator.\n * ${usage}\n */\n`;

const block = (selector: string, lines: string[]) =>
  `${selector} {\n${lines.map((line) => `  ${line}`).join("\n")}\n}\n`;

const tokenLines = (scheme: ColorScheme, prefix: string) =>
  tokenNames.map((name) => `${prefix}${name}: ${theme.colors[scheme][name]};`);

/** The website: shadcn's plain variables for light (`:root`) and dark (`.dark`). */
export const webThemeCss = () =>
  [
    banner("Import it from the web app's global stylesheet."),
    block(":root", [
      ...tokenLines("light", "--"),
      `--radius: ${theme.radius};`,
    ]),
    block(".dark", tokenLines("dark", "--")),
  ].join("\n");

/**
 * The native app (Nativewind): the variables must exist in `@theme` (so Tailwind makes the
 * classes) and in `:root` (default values at runtime). Light is the default; the app's theme
 * provider swaps in the dark values when the device is in dark mode.
 */
export const nativeThemeCss = () =>
  [
    banner("Import it from the native app's global stylesheet."),
    block("@theme", tokenLines("light", "--color-")),
    block(":root", tokenLines("light", "--color-")),
  ].join("\n");

/**
 * The native app's Metro config is plain CommonJS and cannot import TypeScript, so it reads
 * the variable names from this generated JSON instead.
 */
export const nativeThemeVariablesJson = () =>
  `${JSON.stringify(themeVariableNames, null, 2)}\n`;
