import type { Environment, Folder, KeyDef, KeySet } from "./define";
import { isRequired } from "./define";

/*
 * Pure functions that turn key definitions into the three things we generate: an Infisical
 * seed plan, a local .env, and .env.example. No file or network access, so they are easy to
 * test. The commands in cli.ts do the actual writing.
 */

export interface NamedKey extends KeyDef {
  key: string;
}

/** Flattens the registry into one list, and refuses a key defined twice. */
export const flattenKeys = (registry: KeySet[]): NamedKey[] => {
  const seen = new Set<string>();
  const result: NamedKey[] = [];
  for (const { definitions } of registry) {
    for (const [key, definition] of Object.entries(definitions)) {
      if (seen.has(key)) {
        throw new Error(`Environment key ${key} is defined more than once.`);
      }
      seen.add(key);
      result.push({ ...definition, key });
    }
  }
  return result;
};

export interface SeedPlan {
  auto: { folder: Folder; key: string; value: string }[];
  manual: { folder: Folder; hint: string; key: string }[];
}

/**
 * Which keys we can fill in for an environment, and which need a human.
 * Optional keys with no value are neither: nobody needs to be told about them.
 */
export const buildSeedPlan = (
  registry: KeySet[],
  environment: Environment
): SeedPlan => {
  const plan: SeedPlan = { auto: [], manual: [] };
  for (const definition of flattenKeys(registry)) {
    const { folder, key } = definition;
    const value = definition.auto?.(environment);
    if (value !== undefined) {
      plan.auto.push({ folder, key, value });
    } else if (
      isRequired(definition) ||
      definition.requiredIn?.includes(environment)
    ) {
      plan.manual.push({
        folder,
        hint: definition.hint ?? definition.description,
        key,
      });
    }
  }
  return plan;
};

export interface LocalEnv {
  /** Lines for the .env file, in order. */
  lines: string[];
  values: Record<string, string>;
}

/** Everything needed to run on one machine with no accounts. Keys with no local value are left out. */
export const buildLocalEnv = (registry: KeySet[]): LocalEnv => {
  const lines = [
    "# Written by `pnpm setup:local`. Local development only; this file is git-ignored.",
    "# Optional services are described in .env.example. Leave them out and those features stay off.",
  ];
  const values: Record<string, string> = {};
  for (const definition of flattenKeys(registry)) {
    const value = definition.local ?? definition.auto?.("dev");
    if (value !== undefined) {
      lines.push(
        "",
        `# ${definition.description}`,
        `${definition.key}=${value}`
      );
      values[definition.key] = value;
    }
  }
  return { lines, values };
};

const EXAMPLE_HEADER = [
  "# Secrets live in Infisical (project: starterkit). This file only lists key names; never commit real values.",
  "# Infisical dashboard: https://app.infisical.com  (docs: https://infisical.com/docs/documentation/getting-started/introduction)",
  "#",
  "# Two ways to get a working .env:",
  "#   1. Infisical:   `infisical login`, then `pnpm secrets:seed dev` fills what it can generate",
  "#                   and lists the rest (see packages/env/README.md).",
  "#   2. No accounts: `pnpm setup:local` writes a root .env for running on one machine.",
  "#",
  "# GENERATED by `pnpm env:example` from the key definitions. Do not edit by hand.",
].join("\n");

/** "Optional." or, for a key some environments need, where it is required. */
const optionalNote = (definition: KeyDef): string =>
  definition.requiredIn?.length
    ? `Required in ${definition.requiredIn.join(", ")}; optional elsewhere.`
    : "Optional.";

/** The text of .env.example: every key with its description, grouped by Infisical folder. */
export const buildExample = (registry: KeySet[]): string => {
  const keys = flattenKeys(registry);
  const sections = [EXAMPLE_HEADER];
  for (const folder of new Set(keys.map((definition) => definition.folder))) {
    const lines = [`# --- Infisical path: ${folder} ---`];
    for (const definition of keys.filter((entry) => entry.folder === folder)) {
      const notes = [
        definition.description,
        isRequired(definition) ? "" : optionalNote(definition),
        definition.hint ? `Where: ${definition.hint}` : "",
      ].filter(Boolean);
      lines.push(
        "",
        `# ${notes.join(" ")}`,
        `${definition.key}=${definition.local ?? ""}`
      );
    }
    sections.push(lines.join("\n"));
  }
  return `${sections.join("\n\n")}\n`;
};
