import { readdirSync } from "node:fs";
import path from "node:path";

/*
 * Writes src/resources.ts, the file that bundles every catalog. Bundlers (Next.js, Metro)
 * and Node need each JSON import spelled out, so the file lists them all, and this generator
 * writes that list from the folders in src/locales. Adding a language or a namespace is then
 * one step: add the JSON files and run `pnpm catalogs:generate`. A test fails if the file is stale.
 */

/** Locale code -> the namespaces (JSON file names without `.json`) it has. */
export type Listing = Record<string, string[]>;

const NAME = /^[a-z][a-zA-Z0-9]*$/u;

const capitalize = (text: string) =>
  `${text.charAt(0).toUpperCase()}${text.slice(1)}`;

/** Reads `src/locales/<locale>/<namespace>.json` into a listing. */
export const readListing = (localesDir: string): Listing =>
  Object.fromEntries(
    readdirSync(localesDir, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => [
        entry.name,
        readdirSync(path.join(localesDir, entry.name))
          .filter((file) => file.endsWith(".json"))
          .map((file) => file.slice(0, -".json".length)),
      ])
  );

/**
 * The text of resources.ts for a listing. Everything is sorted so the output never depends
 * on the order files were read in.
 */
export const buildResourcesSource = (listing: Listing): string => {
  const locales = Object.keys(listing).toSorted();
  for (const name of [...locales, ...Object.values(listing).flat()]) {
    if (!NAME.test(name)) {
      throw new Error(
        `"${name}" cannot be used as a locale or namespace name: use letters and digits, starting with a lowercase letter.`
      );
    }
  }
  const namespaces = [...new Set(Object.values(listing).flat())].toSorted();
  const identifier = (locale: string, namespace: string) =>
    `${locale}${capitalize(namespace)}`;

  const imports = locales.flatMap((locale) =>
    (listing[locale] ?? [])
      .toSorted()
      .map(
        (namespace) =>
          `import ${identifier(locale, namespace)} from "./locales/${locale}/${namespace}.json";`
      )
  );
  const entries = locales.map((locale) => {
    const inner = (listing[locale] ?? [])
      .toSorted()
      .map(
        (namespace) => `    ${namespace}: ${identifier(locale, namespace)},`
      );
    return `  ${locale}: {\n${inner.join("\n")}\n  },`;
  });

  return `/*
 * GENERATED by \`pnpm catalogs:generate\` from the folders in src/locales.
 * Do not edit by hand: add or remove catalog files, then run the generator.
 */
${imports.join("\n")}

/** Every catalog, bundled statically so no language ever waits for a network request. */
export const resources = {
${entries.join("\n")}
} as const;

/** Namespaces: one JSON file per area, so a screen can ask for only what it needs. */
export const namespaces = [${namespaces.map((name) => `"${name}"`).join(", ")}] as const;
export type Namespace = (typeof namespaces)[number];

export const defaultNamespace: Namespace = "common";
`;
};
